version: '3'
services:
  kibana:
    mem_limit: 512m
    build: .
    container_name: kibana_c_el
    image: kibana_i_el:1.0.4
    ports:
      - 5601:5601
    networks:
      - default
      - shared-network

networks:
  shared-network:
    external: true
