version: '3'
services:
  elasticsearch:
    build: .
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ../data/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - default
      - shared-network

networks:
  shared-network:
    external: true
